Sends emails when rent is created
wolox-training/dmgr-rails pull request #13
Opened 2018-09-04 21:19 UTC by Drocheg

-Adds .env with environment variables
-Adds secrets from config/secrets.yml as environment variables
-Adds mail trap configuration
-Adds mailer to send the email when rent is created
-Adds sidekiq gem
-Adds dotenv gem

2018-09-04 21:19 UTC, Drocheg commented
https://trello.com/c/MltS60dh/11-mandar-email-al-usuario-cuando-se-crea-un-rent

2018-09-05 13:40 UTC, Gmarn requested changes

2018-09-05 13:40 UTC, Gmarn commented on app/controllers/api/v1/rents_controller.rb
> +          RentMailer.new_rent_notification(@rent.id).deliver_later
I recently realize, the `@` here is useless here for define the object rent. Any doubt on why ask me.

2018-09-05 13:40 UTC, Gmarn commented on config/secrets.yml
> +  mailer_domain: <%= ENV["MAILER_DOMAIN"] %>
Here, it is not important but do not forgot to add this at least at you production environment. You can use deftault env or import ones from dev in prod

2018-09-05 13:40 UTC, Gmarn commented on app/views/rent_mailer/new_rent_notification.html.erb
> +<h1>R</h1>
You can delete this file if you are not using it.

2018-09-05 14:11 UTC, Gmarn approved these changes

2018-09-05 14:14 UTC, merged