Book sugestions
wolox-training/dmgr-rails pull request #17
Opened 2018-09-10 19:44 UTC by Drocheg

Adds book sugestion model

2018-09-10 19:44 UTC, Drocheg commented
https://trello.com/c/Fz8Ja2Ug/29-crear-modelo-de-booksuggestion

2018-09-11 15:30 UTC, Gmarn requested changes

2018-09-11 15:30 UTC, Gmarn commented on app/models/book_sugestion.rb
> +  has_one :user, dependent: :destroy
Are you sure you want a  `dependent: :destroy`? 
[Here](https://guides.rubyonrails.org/association_basics.html) some help.

2018-09-11 15:30 UTC, Gmarn commented on db/migrate/20180910185811_create_book_sugestions.rb
> +      t.references :user, foreign_key: true
Were you able to create a boo suggestion without an user?

2018-09-11 16:22 UTC, Drocheg commented on db/migrate/20180910185811_create_book_sugestions.rb
> +      t.references :user, foreign_key: true
In rails console, yes.

2018-09-12 12:47 UTC, Gmarn approved these changes

2018-09-12 13:08 UTC, merged