Installs and configure Devise
wolox-training/dmgr-rails pull request #4
Opened 2018-08-15 14:15 UTC by Drocheg

-Creates users with the default columns created by Devise
-Adds first_name and last_name columns to users

2018-08-15 14:28 UTC, Gmarn requested changes
Now you have travis running I will like it before start correction on that. So please do me a rebase and when build passed I look on the PR ;)

2018-08-15 16:34 UTC, Gmarn submitted a review, later dismissed

2018-08-15 16:34 UTC, Gmarn commented on db/migrate/20180815132933_add_name_to_user.rb
> +    add_column :users, :first_name, :string
It is seems you forgot `first_name` is a required columns.

2018-08-15 16:34 UTC, Gmarn commented on db/migrate/20180815132933_add_name_to_user.rb
> +    add_column :users, :last_name, :string
same for `last_name`

2018-08-21 18:57 UTC, leoncalermo requested changes
just that small change and we are ready to go!

2018-08-21 18:57 UTC, leoncalermo commented on db/migrate/20180815180513_add_required_to_user_name.rb
> +    change_column_null :users, :first_name, false
I like this approach, but...  knowing that this the migration where you are creating this column is in this same PR i would recommend to update the migration where you  added them for the first time. the `AddNameToUser` one. you need to make a rollback to that migration, then update it, and then run it again.

2018-08-21 19:48 UTC, leoncalermo approved these changes
![todo bien](https://media.giphy.com/media/Y01jP8QeLOox2/giphy.gif)

2018-08-21 19:51 UTC, merged